# This action was derived from two main sources:
# 1) https://solutions.posit.co/operations/deploy-methods/ci-cd/github-actions/
# 2) https://rstudio.github.io/renv/articles/ci.html
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - main #you may need to change this if your main branch has a different name
    paths-ignore:
      - 'README.md' #don't re-deploy the app if only the README changes

name: deploy-to-connect

jobs:
  deploy-to-connect:
    runs-on: macOS-latest
    env:
      APP_NAME: "my-shiny-app" #this is the URL "slug"
      APP_DIR: "app"
      ACCESS_TYPE: "logged_in" #options are "all", "logged_in", or "acl"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} #Not sure if this is necessary
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Install packages required for rsconnect
        shell: Rscript {0}
        run: |
          if (!requireNamespace("packrat", quietly = TRUE)) install.packages("packrat")
          if (!requireNamespace("rsconnect", quietly = TRUE)) install.packages("rsconnect")
          if (!requireNamespace("Cairo", quietly = TRUE)) install.packages("Cairo")
          
      - name: Generate manifest.json
        run: |
          rsconnect::writeManifest(appDir = "${{ env.APP_DIR }}")
        shell: Rscript {0}

# For more detailed documentation on this step see
# https://github.com/rstudio/actions/tree/main/connect-publish

      - name: Deploy to RStudio Connect
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://${{ secrets.CONNECT_APIKEY }}@${{ secrets.CONNECT_URL }}
          access-type: ${{ env.ACCESS_TYPE }}
          show-logs: true
          force: true
          dir: ${{ env.APP_DIR }}/:${{ env.APP_NAME }}
          require-vanity-path: true
